[common-etcd]
host = "127.0.0.1:2379"
basePath = "/gochat_srv"
serverPathLogic = "LogicRpc"
serverPathConnect = "ConnectRpc"
userName = ""
password = ""
connectionTimeout = 5

[common-redis]
redisAddress = "172.18.0.76:6480"
redisPassword = ""
db = 6

[common-mysql]
dsn = "oa:QAJZGNx2SrLcgysriuZfg8gSDnJUSE9b@tcp(172.18.0.76:3306)/gochat?charset=utf8mb4&parseTime=True"